
build:fedora:
  image: fedora:29
  script:
  - dnf -y install puppet make tito
  - tito build --test --rpm
  - mkdir build
  - mv /tmp/tito/* build/
  artifacts:
    paths:
    - build/

build:centos:
  image: centos:7
  script:
  - yum -y install epel-release
  - yum -y install puppet make tito
  - tito build --test --rpm
  - mkdir build
  - mv /tmp/tito/* build/
  artifacts:
    paths:
    - build/
