.job_template: &fedora_prep
  image: fedora
  before_script:
    - dnf -y install puppet make tito

      
.job_template: &centos_prep
  image: centos:7
  before_script:
    - yum -y install epel-release
    - yum -y install puppet make tito


.job_template: &amazonlinux_prep
  image: amazonlinux
  before_script:
    - amazon-linux-extras install -y epel
    - yum -y install puppet make tito

      
.job_template: &build_script
  script:
  - tito build --test --rpm
  - mkdir build
  - find /tmp/tito/ -name *.rpm -exec mv {} build \;
  artifacts:
    paths:
    - build/*

stages:
  - build
  - package
  - test


make:
  stage: build
  image: fedora
  before_script:
    - dnf -y install puppet make findutils
  script:
    - make
    - make check
    - make install
    - make clean
    - make
  artifacts:
    paths:
    - build/*

fedora:
  stage: build
  <<: *fedora_prep
  <<: *build_script

centos:
  stage: build
  <<: *centos_prep
  <<: *build_script

amazonlinux:
  stage: build
  <<: *amazonlinux_prep
  <<: *build_script

package:
  stage: package
  image: fedora
  script:
    - dnf -y builddep build/*.fc*.src.rpm
    - rpm -ivh build/*.fc*.src.rpm
    - rpmbuild -ba ~/build/SPECS/*.spec
    - find ~/rpmbuild/ -name *.rpm  -exec mv {} build \;
  artifacts:
    paths:
    - build/*

