
build:fedora:
  image: fedora:29
  script:
  - dnf -y install puppet make tito
  - make check
  - tito build --test --rpm
  artifacts:
    paths:
    - /tmp/tito/

build:centos:
  image: centos:7
  script:
  - yum -y install epel-release
  - yum -y install puppet make tito
  - make check
  - tito build --test --rpm
  artifacts:
    paths:
    - /tmp/tito/
